### ISSUE TITLE
nested tabs not possible?

### ISSUE THREAD

**Issue by awrog** [getgrav/grav-plugin-shortcode-ui#26] opened 2018-07-03 06:59 UTC
I would like to create a [ui-tabs ..] construct within a [ui-tab ...] (nested tabs)
This causes an errror:
E_RECOVERABLE_ERROR - Argument 1 passed to Grav\Plugin\ShortcodeManager::getId() must implement interface Thunder\Shortcode\Shortcode\ShortcodeInterface, null given, called in /home/lrpdoc/domains/lrp-doc.pkn.nl/public_html/user/plugins/shortcode-ui/shortcodes/TabsShortcode.php on line 34 and defined

**Comment by rhukster** [comment] 2019-02-01 04:39
Duplicate of this issue: #29

**Closed as completed by rhukster** 2019-02-01 04:39 UTC
Labels: duplicate
